### ISSUE TITLE
number chaining overkill?

### ISSUE THREAD

**Issue by juliangruber** [deanlandolt/bytewise-uri#1]
```
// Number literal shorthand syntax can be chained:

keyEq('10+9.5+3', 22.5)
```

this looks similarish to

```
key('10+')
```

**Comment by deanlandolt** [comment]
I just pushed up some parser fixes from last night that are still a bit of a WIP. The idea is to tighten up the language and strip out any features we don't need. Number chaining was the first thing to go -- it never really held together well anyway.
