### ISSUE TITLE
Food for thought: ES6 tagged templates

### ISSUE THREAD

**Issue by jtremback** [deanlandolt/bytewise-uri#2]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

**Comment by deanlandolt** [comment]
https://github.com/deanlandolt/bytewise-uri#template-strings :D

**Comment by deanlandolt** [comment]
FWIW that's only partially implemented -- the template/query stuff was blocked by the need for range support in bytewise. Now that that's about done I plan on revisting templates in bytewise-uri sometime soon and finishing them up. This should make life a whole lot easier when trying to define keypaths and build out subspaces and the like.

**Comment by jtremback** [comment]
Whoops, sorry about the dumb issue. Great work!
